# Intro.  

[`numpy`](https://numpy.org/)와 [`matplotlib`](https://matplotlib.org/)에 대해 정리한다.  
numpy는 파이썬에서 널리 사용되는 산술 연산 관련 라이브러리다. 머신러닝 공부하면 거의 필수, de facto standard급으로 등장한다.  
matplotlib은 약간.. 밀리긴 하지만 그래도 잘쓰는 plot 라이브러리다.  


## 1. Numpy

넘파이에 대해 간략하게 정리한다.  

### 1.1. Import

In [1]:
import numpy as np

관례상으로 numpy의 alias를 np로 걸어준다. 정신건강을 위해 관례를 지키자.  

### 1.2. Numpy Array

numpy 배열을 생성해보자.  

In [3]:
x = np.array([1.0, 2.0, 3.0])
print(type(x))
print(x.dtype)
print(x.shape)

<class 'numpy.ndarray'>
float64
(3,)


다차원 배열(행렬)도 생성 가능하다.

In [4]:
x = np.array([[1, 2], [3, 4]])
e = np.array([[1, 0], [0, 1]])

### 1.3. 넘파이 산술 연산

In [10]:
print(x + e)
print(x - e)

[[2 2]
 [3 5]]
[[0 2]
 [3 3]]


좋다. 상식 선에서 나온다. 하지만 다음을 보자.

In [11]:
x * e

array([[1, 0],
       [0, 4]])

네? 단위 행렬을 곱했는데 결과가 왜이래요? 사실 이것은 단위 행렬을 곱한 것이 아니고 numpy의 `brodcasting` 연산이 적용된 것이다.  
우리가 알고있던 행렬의 곱을 하려면 다음과 같이 코드를 써야한다.

In [12]:
np.matmul(x, e)

array([[1, 2],
       [3, 4]])

이제 비로소 상식적으로 동작하는 모습을 확인하였다. ㅇㅅㅇ)/

### 1.4. 브로드캐스트

보통 행렬의 곱셈을 떠올리면 넘파이 배열을 이해하기 어려울 것이다. 넘파이는 shape이 다른 행렬끼리도 계산이 가능하다.

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
A * B

array([[10, 40],
       [30, 80]])

신기하게 느껴질 수도 있는데 이는 다음과 같이 계산 된 것이다.  

넘파이 배열 A가 있다고 가정해보자.  

|1|2|
|-|-|
|3|4|

그리고 다음이 뒤에 곱해지는 넘파이 배열이 내부적으로 표현되는 모습이다.

|10|20|
|-|-|
|10|20|

그리고 각자에 대해 정직하게(?) 곱해지기 때문에 결과가 앞선 코드와 같이 나온 것이다.

### 1.5. 원소 접근

원소 접근은 파이썬의 리스트(혹은 다른 언어들의 배열)을 떠올리면 간단하다.

In [15]:
A

array([[1, 2],
       [3, 4]])

In [16]:
A[0]

array([1, 2])

In [17]:
A[1]

array([3, 4])

In [18]:
A[0][0]

1